server:
  port: 8080 # ?? ??
  servlet:
    context-path: / # ???? ??
    encoding:
      charset: UTF-8
      enabled: true
      force: true



spring:
  datasource:

    url: jdbc:mysql://localhost:3306/groupware?serverTimezone=UTC  # ?????? URL
    username: root                              # ?????? ??? ??
    password: 1234                              # ?????? ????
    jpa:
      hibernate:
        ddl-auto: update                        # Hibernate? DDL ?? ??
        show-sql: true                          # ??? SQL? ??? ??

  application:
    name: groupware # ?????? ??

logging:
  level:
    root: info
    org.groupware.project: debug # org.groupware.project ? ?? ??? ?? ??

